--
--   TABLES
--
CREATE TABLE COUNTRY (
    ID INTEGER,
    ISO_CODE varchar(255),
    NAME varchar(255)
);

CREATE TABLE CUSTOMER (
    ID INTEGER,
    USERNAME varchar(255),
    PASSWORD varchar(255),
    LAST_NAME varchar(255),
    FIRST_NAME varchar(255),
    BIRTHDAY date,
    COUNTRY_ID INTEGER,
    CREATED_ON timestamp,
    UPDATED_ON timestamp
);

CREATE TABLE CUST_ADDRESS (
    ID INTEGER,
    CUSTOMER_ID INTEGER,
    STREET varchar(255),
    STREET_NBR varchar(255),
    CITY varchar(255),
    ZIP_CODE varchar(255),
    COUNTRY_ID INTEGER,
    PHONE varchar(255),
    MOBILE varchar(255),
    TYPE varchar(255)
);

CREATE TABLE CUST_PAYMENT (
    ID INTEGER,
    CUSTOMER_ID INTEGER,
    PROVIDER varchar(255),
    ACCOUNT_NBR varchar(255),
    EXPIRATION_DATE date
);

CREATE TABLE PRODUCT (
    ID INTEGER,
    NAME varchar(255),
    DESCRIPTION varchar(255),
    PRICE DECIMAL,
    SKU varchar(255),
    STATUS varchar(255),
    CATEGORY_ID INTEGER,
    INVENTORY_ID INTEGER UNIQUE,
    CREATED_ON timestamp,
    UPDATED_ON timestamp
);

CREATE TABLE PRODUCT_CATEGORY (
    ID INTEGER,
    NAME varchar(255),
    DESCRIPTION varchar(255),
    CREATED_ON timestamp,
    UPDATED_ON timestamp
);

CREATE TABLE PRODUCT_INVENTORY (
    ID INTEGER,
    QUANTITY INTEGER,
    CREATED_ON timestamp,
    UPDATED_ON timestamp
);

CREATE TABLE ORDERS (
    ID INTEGER,
    CUST_ID INTEGER NOT NULL,
    PAYMENT_ID INTEGER,
    STATUS varchar(255),
    AMOUNT DECIMAL,
    CREATED_ON timestamp,
    UPDATED_ON timestamp
);

CREATE TABLE ORDER_ITEM (
    ID INTEGER,
    ORDER_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    quantity INTEGER DEFAULT 1
);

CREATE TABLE PAYMENT_DETAIL (
    ID INTEGER,
    AMOUNT DECIMAL,
    PROVIDER varchar(255),
    PROVIDER_PAYMENT_UUID varchar(255)
);

--
-- CONSTRAINTS
--
ALTER TABLE COUNTRY ADD CONSTRAINT COUNTRY_PK PRIMARY KEY (ID);
ALTER TABLE COUNTRY ADD CONSTRAINT COUNTRY_UQ01 UNIQUE (ISO_CODE);

ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY (ID);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_FK01 FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (ID);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_UQ01 UNIQUE (USERNAME);

ALTER TABLE CUST_ADDRESS ADD CONSTRAINT CUST_ADDRESS_PK PRIMARY KEY (ID);
ALTER TABLE CUST_ADDRESS ADD CONSTRAINT CUST_ADDRESS_FK01 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID);

ALTER TABLE CUST_PAYMENT ADD CONSTRAINT CUST_PAYMENT_PK PRIMARY KEY (ID);
ALTER TABLE CUST_PAYMENT ADD CONSTRAINT CUST_PAYMENT_FK01 FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID);

ALTER TABLE PRODUCT_CATEGORY ADD CONSTRAINT PRODUCT_CATEGORY_PK PRIMARY KEY (ID);
ALTER TABLE PRODUCT_INVENTORY ADD CONSTRAINT PRODUCT_INVENTORY_PK PRIMARY KEY (ID);

ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PK PRIMARY KEY (ID);
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_FK01 FOREIGN KEY (CATEGORY_ID) REFERENCES PRODUCT_CATEGORY (ID);
ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_FK02 FOREIGN KEY (INVENTORY_ID) REFERENCES PRODUCT_INVENTORY (ID);

ALTER TABLE PAYMENT_DETAIL ADD CONSTRAINT PAYMENT_DETAIL_PK PRIMARY KEY (ID);

ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_PK PRIMARY KEY (ID);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_FK01 FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT_DETAIL (ID);
ALTER TABLE ORDERS ADD CONSTRAINT ORDERS_FK02 FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (ID);

ALTER TABLE ORDER_ITEM ADD CONSTRAINT ORDER_ITEM_PK PRIMARY KEY (ID);
ALTER TABLE ORDER_ITEM ADD CONSTRAINT ORDER_ITEM_FK01 FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID);
ALTER TABLE ORDER_ITEM ADD CONSTRAINT ORDER_ITEM_FK02 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID);
ALTER TABLE ORDER_ITEM ADD CONSTRAINT ORDER_ITEM_UQ01 UNIQUE (ORDER_ID, PRODUCT_ID);


--
-- SEQUENCES
--
CREATE SEQUENCE COUNTRY_SEQ AS INTEGER START WITH 100000 INCREMENT BY 1;
CREATE SEQUENCE CUSTOMER_SEQ AS INTEGER START WITH 100000 INCREMENT BY 1;
CREATE SEQUENCE CUST_ADDRESS_SEQ AS INTEGER START WITH 100000 INCREMENT BY 1;
CREATE SEQUENCE CUST_PAYMENT_SEQ AS INTEGER START WITH 100000 INCREMENT BY 1;
CREATE SEQUENCE PRODUCT_SEQ AS INTEGER START WITH 100000 INCREMENT BY 1;
CREATE SEQUENCE PRODUCT_CATEGORY_SEQ AS INTEGER START WITH 100000 INCREMENT BY 1;
CREATE SEQUENCE PRODUCT_INVENTORY_SEQ AS INTEGER START WITH 100000 INCREMENT BY 1;
CREATE SEQUENCE ORDERS_SEQ AS INTEGER START WITH 100000 INCREMENT BY 1;
CREATE SEQUENCE ORDER_ITEM_SEQ AS INTEGER START WITH 100000 INCREMENT BY 1;
CREATE SEQUENCE PAYMENT_DETAIL_SEQ AS INTEGER START WITH 100000 INCREMENT BY 1;
